class API:
    def __init__(self, url: str) -> None: ...
    def __truediv__(self, other: str) -> "API": ...

class JobAPI(API):
    def __init__(self, job_id: str, api: API) -> None: ...
    @property
    def file(self) -> API: ...
    @property
    def status(self) -> API: ...
